In [21]:
import requests
from bs4 import BeautifulSoup
import certifi
import csv

In [3]:
import requests
from bs4 import BeautifulSoup
import urllib3

# Disable SSL warnings
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

url = 'https://erp.powergrid.gov.bd/web/generations/view_generations'

# Bypass SSL verification (use cautiously!)
response = requests.get(url, verify=False)

# Continue with scraping...
soup = BeautifulSoup(response.content, 'html.parser')
# ... (rest of your scraping code)

In [4]:
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1, viewport-fit=cover" name="viewport"/>
  <meta content="ie=edge" http-equiv="X-UA-Compatible"/>
  <meta content="" name="msapplication-TileColor"/>
  <meta content="black-translucent" name="apple-mobile-web-app-status-bar-style"/>
  <meta content="yes" name="apple-mobile-web-app-capable"/>
  <meta content="yes" name="mobile-web-app-capable"/>
  <meta content="True" name="HandheldFriendly"/>
  <meta content="320" name="MobileOptimized"/>
  <!-- PWA  -->
  <meta content="#6777ef" name="theme-color"/>
  <link href="https://erp.powergrid.gov.bd/images/logo_r.png" rel="apple-touch-icon"/>
  <!--<link rel="manifest" href="https://erp.powergrid.gov.bd/manifests/transgrid.json"> -->
  <title>
   PGCB Website
  </title>
  <link href="https://erp.powergrid.gov.bd/favicon.ico" rel="icon" type="image/x-icon">
   <link href="https://erp.powergrid.gov.bd/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
   <link href="https://erp.powergrid.gov.bd/dist/css/tabler.min.css" rel="stylesheet"/>
   <link href="https://erp.powergrid.gov.bd/dist/css/tabler-flags.min.css" rel="stylesheet"/>
   <link href="https://erp.powergrid.gov.bd/dist/css/tabler-payments.min.css" rel="stylesheet"/>
   <link href="https://erp.powergrid.gov.bd/dist/css/tabler-vendors.min.css" rel="stylesheet"/>
   <link href="https://erp.powergrid.gov.bd/dist/css/demo.min.css" rel="stylesheet"/>
   <link href="https://erp.powergrid.gov.bd/css/bootstrap-datepicker.min.css" rel="stylesheet"/>
   <!-- Styles -->
   <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"/>
   <link href="https://cdn.jsdelivr.net/npm/select2-bootstrap-5-theme@1.3.0/dist/select2-bootstrap-5-theme.min.css" rel="stylesheet"/>
   <link href="https://cdn.datatables.net/buttons/2.0.1/css/buttons.dataTables.min.css" rel="stylesheet"/>
   <!-- Tabler CSS -->
   <!-- DataTables CSS -->
   <link href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css" rel="stylesheet"/>
   <style>
    /* Chrome, Safari, Edge, Opera */
    input[type=number]::-webkit-inner-spin-button,
    input[type=number]::-webkit-outer-spin-button {
        -webkit-appearance: none;
        margin: 0;
    }

    /* Firefox */
    input[type=number] {
        -moz-appearance: textfield;
    }

    .tooltip-inner {
        white-space: pre-line;
    }
    .svg_small
    {
        transform: scale(0.7);
    }
    @font-face {
        font-family: Kalpurush;
        src: url(https://erp.powergrid.gov.bd/fonts/kalpurush.ttf);
    }
    @font-face {
        font-family: SolaimanLipi;
        src: url(https://erp.powergrid.gov.bd/fonts/SolaimanLipi.ttf);
    }
    .bn{
        font-family: SolaimanLipi !important;
    }
    @import url('https://rsms.me/inter/inter.css');

    :root {
        --tblr-font-sans-serif: 'Inter Var', -apple-system, BlinkMacSystemFont, San Francisco, Segoe UI, Roboto, Helvetica Neue, sans-serif;
    }

    body {
        font-feature-settings: "cv03", "cv04", "cv11";
    }

    .delbtn{
        text-decoration: none; border: none; background: none; color: darkred;
    }
   </style>
   <style>
    @import url('https://rsms.me/inter/inter.css');
    :root {
        --tblr-font-sans-serif:  'Inter Var', -apple-system, BlinkMacSystemFont, San Francisco, Segoe UI, Roboto, Helvetica Neue, sans-serif;
    }
    body {
        font-feature-settings: "cv03", "cv04", "cv11";
    }
   </style>
  </link>
 </head>
 <body>
  <!--<body class="layout-fluid">-->
  <div class="page">
   <div class="sticky-top">
    <header class="navbar navbar-expand-md navbar-light d-print-none">
     <div class="container-xl">
      <button aria-controls="navbar-menu" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-bs-target="#navbar-menu" data-bs-toggle="collapse" type="button">
       <span class="navbar-toggler-icon">
       </span>
      </button>
      <h1 class="navbar-brand navbar-brand-autodark d-none-navbar-horizontal pe-0 pe-md-3">
       <a href="https://pgcb.gov.bd/" style="font-size: 15px; font-weight: normal; text-decoration: none; font-family: Arial, Helvetica, sans-serif !important;">
        <img alt="PGCB" class="navbar-brand-image" height="32" src="https://erp.powergrid.gov.bd/images/logo_r.png" width="32"/>
        Back to Website
       </a>
      </h1>
      <div class="navbar-nav flex-row order-md-last">
       <a class="nav-link d-flex lh-1 text-reset p-0" href="https://erp.powergrid.gov.bd/login">
        <svg class="icon icon-tabler icon-tabler-login" fill="none" height="24" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">
         <path d="M0 0h24v24H0z" fill="none" stroke="none">
         </path>
         <path d="M14 8v-2a2 2 0 0 0 -2 -2h-7a2 2 0 0 0 -2 2v12a2 2 0 0 0 2 2h7a2 2 0 0 0 2 -2v-2">
         </path>
         <path d="M20 12h-13l3 -3m0 6l-3 -3">
         </path>
        </svg>
        Sign in
       </a>
      </div>
      <div class="collapse navbar-collapse" id="navbar-menu">
       <div class="d-flex flex-column flex-md-row flex-fill align-items-stretch align-items-md-center">
        <ul class="navbar-nav">
        </ul>
       </div>
      </div>
     </div>
    </header>
   </div>
   <div class="page-wrapper">
    <div class="page-header d-print-none">
     <div class="container-xl">
      <div class="row g-2 align-items-center">
       <div class="col">
        <h2 class="page-title">
         Hourly generation and Load shed
        </h2>
       </div>
      </div>
     </div>
    </div>
    <div class="page-body">
     <div class="container-xl">
      <style>
       table, th, td {
            text-align: center;
            padding: 5px;
        }
      </style>
      <div class="row">
       <div class="col-sm-3">
        <form accept-charset="UTF-8" action="https://erp.powergrid.gov.bd/web/generations/view_generations" method="GET">
         <input class="form-control" id="search" name="search" placeholder="Search by Date" style="margin: 5px; margin-left: 0px;" type="text" value=""/>
         <button class="btn btn-sm btn-success" style="display: none" type="submit">
          Search
         </button>
        </form>
       </div>
       <div class="col-sm-9">
       </div>
      </div>
      <div class="card">
       <div class="card-body">
        <table class="table-bordered" style=" border-color: #e2e8f0; ">
         <!-- <table class="table table-vcenter card-table ">-->
         <thead>
          <tr>
           <th rowspan="2" style="width: 80px;">
            Date
           </th>
           <th rowspan="2">
            Time
           </th>
           <th rowspan="2">
            Generation(MW)
           </th>
           <th rowspan="2">
            Demand(MW)
           </th>
           <th rowspan="2">
            Loadshed
           </th>
           <th rowspan="2">
            Gas
           </th>
           <th rowspan="2">
            Liquid Fuel
           </th>
           <th rowspan="2">
            Coal
           </th>
           <th rowspan="2">
            Hydro
           </th>
           <th rowspan="2">
            Solar
           </th>
           <th rowspan="2">
            Wind
           </th>
           <th colspan="3" rowspan="1">
            India
           </th>
           <th rowspan="2">
            Nepal
           </th>
           <th rowspan="2" style="width: 100px;">
            Remarks
           </th>
          </tr>
          <tr>
           <th colspan="1" rowspan="1">
            Bheramara HVDC
           </th>
           <th colspan="1" rowspan="1">
            Tripura
           </th>
           <th colspan="1" rowspan="1">
            Adani
           </th>
          </tr>
         </thead>
         <tbody>
          <tr>
           <td class="text-nowrap">
            25-03-2025
           </td>
           <td>
            15:00:00
           </td>
           <td>
            13302
           </td>
           <td>
            13302
           </td>
           <!--<td>0.00</td>-->
           <td>
            0
           </td>
           <td>
            5837
           </td>
           <td>
            1181
           </td>
           <td>
            3478
           </td>
           <td>
            46
           </td>
           <td>
            467
           </td>
           <td>
            40
           </td>
           <td>
            918
           </td>
           <td>
            72
           </td>
           <td>
            1263
           </td>
           <td>
            0
           </td>
           <td>
           </td>
          </tr>
          <tr>
           <td class="text-nowrap">
            25-03-2025
           </td>
           <td>
            14:00:00
           </td>
           <td>
            13253
           </td>
           <td>
            13253
           </td>
           <!--<td>0.00</td>-->
           <td>
            0
           </td>
           <td>
            5909
           </td>
           <td>
            938
           </td>
           <td>
            3480
           </td>
           <td>
            46
           </td>
           <td>
            583
           </td>
           <td>
            28
           </td>
           <td>
            918
           </td>
           <td>
            82
           </td>
           <td>
            1269
           </td>
           <td>
            0
           </td>
           <td>
           </td>
          </tr>
          <tr>
           <td class="text-nowrap">
            25-03-2025
           </td>
           <td>
            13:00:00
           </td>
           <td>
            13048
           </td>
           <td>
            13048
           </td>
           <!--<td>0.00</td>-->
           <td>
            0
           </td>
           <td>
            5949
           </td>
           <td>
            744
           </td>
           <td>
            3420
           </td>
           <td>
            46
           </td>
           <td>
            658
           </td>
           <td>
            27
           </td>
           <td>
            919
           </td>
           <td>
            72
           </td>
           <td>
            1213
           </td>
           <td>
            0
           </td>
           <td>
           </td>
          </tr>
          <tr>
           <td class="text-nowrap">
            25-03-2025
           </td>
           <td>
            12:00:00
           </td>
           <td>
            12734
           </td>
           <td>
            12734
           </td>
           <!--<td>0.00</td>-->
           <td>
            0
           </td>
           <td>
            5959
           </td>
           <td>
            531
           </td>
           <td>
            3408
           </td>
           <td>
            46
           </td>
           <td>
            682
           </td>
           <td>
            6
           </td>
           <td>
            919
           </td>
           <td>
            68
           </td>
           <td>
            1115
           </td>
           <td>
            0
           </td>
           <td>
            Day Peak
           </td>
          </tr>
          <tr>
           <td class="text-nowrap">
            25-03-2025
           </td>
           <td>
            11:00:00
           </td>
           <td>
            12251
           </td>
           <td>
            12251
           </td>
           <!--<td>0.00</td>-->
           <td>
            0
           </td>
           <td>
            5965
           </td>
           <td>
            449
           </td>
           <td>
            3124
           </td>
           <td>
            46
           </td>
           <td>
            659
           </td>
           <td>
            12
           </td>
           <td>
            919
           </td>
           <td>
            64
           </td>
           <td>
            1013
           </td>
           <td>
            0
           </td>
           <td>
           </td>
          </tr>
          <tr>
           <td class="text-nowrap">
            25-03-2025
           </td>
           <td>
            10:00:00
           </td>
           <td>
            11940
           </td>
           <td>
            11940
           </td>
           <!--<td>0.00</td>-->
           <td>
            0
           </td>
           <td>
            6077
           </td>
           <td>
            410
           </td>
           <td>
            2921
           </td>
           <td>
            46
           </td>
           <td>
            577
           </td>
           <td>
            9
           </td>
           <td>
            919
           </td>
           <td>
            58
           </td>
           <td>
            923
           </td>
           <td>
            0
           </td>
           <td>
           </td>
          </tr>
          <tr>
           <td class="text-nowrap">
            25-03-2025
           </td>
           <td>
            09:00:00
           </td>
           <td>
            11375
           </td>
           <td>
            11375
           </td>
           <!--<td>0.00</td>-->
           <td>
            0
           </td>
           <td>
            6078
           </td>
           <td>
            376
           </td>
           <td>
            2710
           </td>
           <td>
            46
           </td>
           <td>
            414
           </td>
           <td>
            6
           </td>
           <td>
            870
           </td>
           <td>
            58
           </td>
           <td>
            817
           </td>
           <td>
            0
           </td>
           <td>
           </td>
          </tr>
          <tr>
           <td class="text-nowrap">
            25-03-2025
           </td>
           <td>
            08:00:00
           </td>
           <td>
            10826
           </td>
           <td>
            10826
           </td>
           <!--<td>0.00</td>-->
           <td>
            0
           </td>
           <td>
            5949
           </td>
           <td>
            314
           </td>
           <td>
            2521
           </td>
           <td>
            46
           </td>
           <td>
            247
           </td>
           <td>
            8
           </td>
           <td>
            870
           </td>
           <td>
            54
           </td>
           <td>
            817
           </td>
           <td>
            0
           </td>
           <td>
           </td>
          </tr>
          <tr>
           <td class="text-nowrap">
            25-03-2025
           </td>
           <td>
            07:00:00
           </td>
           <td>
            10066
           </td>
           <td>
            10066
           </td>
           <!--<td>0.00</td>-->
           <td>
            0
           </td>
           <td>
            5423
           </td>
           <td>
            229
           </td>
           <td>
            2496
           </td>
           <td>
            46
           </td>
           <td>
            77
           </td>
           <td>
            12
           </td>
           <td>
            919
           </td>
           <td>
            40
           </td>
           <td>
            824
           </td>
           <td>
            0
           </td>
           <td>
           </td>
          </tr>
          <tr>
           <td class="text-nowrap">
            25-03-2025
           </td>
           <td>
            06:00:00
           </td>
           <td>
            9802
           </td>
           <td>
            9802
           </td>
           <!--<td>0.00</td>-->
           <td>
            0
           </td>
           <td>
            5182
           </td>
           <td>
            215
           </td>
           <td>
            2542
           </td>
           <td>
            46
           </td>
           <td>
            0
           </td>
           <td>
            16
           </td>
           <td>
            920
           </td>
           <td>
            50
           </td>
           <td>
            831
           </td>
           <td>
            0
           </td>
           <td>
           </td>
          </tr>
          <tr>
           <td class="text-nowrap">
            25-03-2025
           </td>
           <td>
            05:00:00
           </td>
           <td>
            10496
           </td>
           <td>
            10496
           </td>
           <!--<td>0.00</td>-->
           <td>
            0
           </td>
           <td>
            5623
           </td>
           <td>
            266
           </td>
           <td>
            2735
           </td>
           <td>
            46
           </td>
           <td>
            0
           </td>
           <td>
            19
           </td>
           <td>
            919
           </td>
           <td>
            56
           </td>
           <td>
            832
           </td>
           <td>
            0
           </td>
           <td>
           </td>
          </tr>
          <tr>
           <td class="text-nowrap">
            25-03-2025
           </td>
           <td>
            04:00:00
           </td>
           <td>
            11745
           </td>
           <td>
            11745
           </td>
           <!--<td>0.00</td>-->
           <td>
            0
           </td>
           <td>
            5760
           </td>
           <td>
            605
           </td>
           <td>
            3402
           </td>
           <td>
            46
           </td>
           <td>
            0
           </td>
           <td>
            19
           </td>
           <td>
            919
           </td>
           <td>
            64
           </td>
           <td>
            930
           </td>
           <td>
            0
           </td>
           <td>
           </td>
          </tr>
          <tr>
           <td class="text-nowrap">
            25-03-2025
           </td>
           <td>
            03:00:00
           </td>
           <td>
            11754
           </td>
           <td>
            11754
           </td>
           <!--<td>0.00</td>-->
           <td>
            0
           </td>
           <td>
            5967
           </td>
           <td>
            589
           </td>
           <td>
            3124
           </td>
           <td>
            46
           </td>
           <td>
            0
           </td>
           <td>
            29
           </td>
           <td>
            919
           </td>
           <td>
            62
           </td>
           <td>
            1018
           </td>
           <td>
            0
           </td>
           <td>
           </td>
          </tr>
          <tr>
           <td class="text-nowrap">
            25-03-2025
           </td>
           <td>
            02:00:00
           </td>
           <td>
            11393
           </td>
           <td>
            11393
           </td>
           <!--<td>0.00</td>-->
           <td>
            0
           </td>
           <td>
            5667
           </td>
           <td>
            550
           </td>
           <td>
            3087
           </td>
           <td>
            46
           </td>
           <td>
            0
           </td>
           <td>
            37
           </td>
           <td>
            919
           </td>
           <td>
            64
           </td>
           <td>
            1023
           </td>
           <td>
            0
           </td>
           <td>

In [5]:
table = soup.find('table')

In [6]:
table

<table class="table-bordered" style=" border-color: #e2e8f0; ">
<!-- <table class="table table-vcenter card-table ">-->
<thead>
<tr>
<th rowspan="2" style="width: 80px;">Date</th>
<th rowspan="2">Time</th>
<th rowspan="2">Generation(MW)</th>
<th rowspan="2">Demand(MW)</th>
<th rowspan="2">Loadshed</th>
<th rowspan="2">Gas</th>
<th rowspan="2">Liquid Fuel</th>
<th rowspan="2">Coal</th>
<th rowspan="2">Hydro</th>
<th rowspan="2">Solar</th>
<th rowspan="2">Wind</th>
<th colspan="3" rowspan="1">India</th>
<th rowspan="2">Nepal</th>
<th rowspan="2" style="width: 100px;">Remarks</th>
</tr>
<tr>
<th colspan="1" rowspan="1">Bheramara HVDC</th>
<th colspan="1" rowspan="1">Tripura</th>
<th colspan="1" rowspan="1">Adani</th>
</tr>
</thead>
<tbody>
<tr>
<td class="text-nowrap">25-03-2025</td>
<td>15:00:00</td>
<td>13302</td>
<td>13302</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>5837</td>
<td>1181</td>
<td>3478</td>
<td>46</td>
<td>467</td>
<td>40</td>
<td>918</td>
<td>72</td>
<td>1263</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">25-03-2025</td>
<td>14:00:00</td>
<td>13253</td>
<td>13253</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>5909</td>
<td>938</td>
<td>3480</td>
<td>46</td>
<td>583</td>
<td>28</td>
<td>918</td>
<td>82</td>
<td>1269</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">25-03-2025</td>
<td>13:00:00</td>
<td>13048</td>
<td>13048</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>5949</td>
<td>744</td>
<td>3420</td>
<td>46</td>
<td>658</td>
<td>27</td>
<td>919</td>
<td>72</td>
<td>1213</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">25-03-2025</td>
<td>12:00:00</td>
<td>12734</td>
<td>12734</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>5959</td>
<td>531</td>
<td>3408</td>
<td>46</td>
<td>682</td>
<td>6</td>
<td>919</td>
<td>68</td>
<td>1115</td>
<td>0</td>
<td>Day Peak</td>
</tr>
<tr>
<td class="text-nowrap">25-03-2025</td>
<td>11:00:00</td>
<td>12251</td>
<td>12251</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>5965</td>
<td>449</td>
<td>3124</td>
<td>46</td>
<td>659</td>
<td>12</td>
<td>919</td>
<td>64</td>
<td>1013</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">25-03-2025</td>
<td>10:00:00</td>
<td>11940</td>
<td>11940</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>6077</td>
<td>410</td>
<td>2921</td>
<td>46</td>
<td>577</td>
<td>9</td>
<td>919</td>
<td>58</td>
<td>923</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">25-03-2025</td>
<td>09:00:00</td>
<td>11375</td>
<td>11375</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>6078</td>
<td>376</td>
<td>2710</td>
<td>46</td>
<td>414</td>
<td>6</td>
<td>870</td>
<td>58</td>
<td>817</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">25-03-2025</td>
<td>08:00:00</td>
<td>10826</td>
<td>10826</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>5949</td>
<td>314</td>
<td>2521</td>
<td>46</td>
<td>247</td>
<td>8</td>
<td>870</td>
<td>54</td>
<td>817</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">25-03-2025</td>
<td>07:00:00</td>
<td>10066</td>
<td>10066</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>5423</td>
<td>229</td>
<td>2496</td>
<td>46</td>
<td>77</td>
<td>12</td>
<td>919</td>
<td>40</td>
<td>824</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">25-03-2025</td>
<td>06:00:00</td>
<td>9802</td>
<td>9802</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>5182</td>
<td>215</td>
<td>2542</td>
<td>46</td>
<td>0</td>
<td>16</td>
<td>920</td>
<td>50</td>
<td>831</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">25-03-2025</td>
<td>05:00:00</td>
<td>10496</td>
<td>10496</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>5623</td>
<td>266</td>
<td>2735</td>
<td>46</td>
<td>0</td>
<td>19</td>
<td>919</td>
<td>56</td>
<td>832</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">25-03-2025</td>
<td>04:00:00</td>
<td>11745</td>
<td>11745</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>5760</td>
<td>605</td>
<td>3402</td>
<td>46</td>
<td>0</td>
<td>19</td>
<td>919</td>
<td>64</td>
<td>930</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">25-03-2025</td>
<td>03:00:00</td>
<td>11754</td>
<td>11754</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>5967</td>
<td>589</td>
<td>3124</td>
<td>46</td>
<td>0</td>
<td>29</td>
<td>919</td>
<td>62</td>
<td>1018</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">25-03-2025</td>
<td>02:00:00</td>
<td>11393</td>
<td>11393</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>5667</td>
<td>550</td>
<td>3087</td>
<td>46</td>
<td>0</td>
<td>37</td>
<td>919</td>
<td>64</td>
<td>1023</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">25-03-2025</td>
<td>01:00:00</td>
<td>11831</td>
<td>11831</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>5908</td>
<td>596</td>
<td>3219</td>
<td>46</td>
<td>0</td>
<td>24</td>
<td>919</td>
<td>62</td>
<td>1057</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">24-03-2025</td>
<td>24:00:00</td>
<td>12305</td>
<td>12305</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>6034</td>
<td>681</td>
<td>3380</td>
<td>46</td>
<td>0</td>
<td>13</td>
<td>919</td>
<td>68</td>
<td>1164</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">24-03-2025</td>
<td>23:00:00</td>
<td>12741</td>
<td>12741</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>6068</td>
<td>788</td>
<td>3588</td>
<td>46</td>
<td>0</td>
<td>1</td>
<td>919</td>
<td>70</td>
<td>1261</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">24-03-2025</td>
<td>22:00:00</td>
<td>13076</td>
<td>13076</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>6013</td>
<td>959</td>
<td>3754</td>
<td>46</td>
<td>0</td>
<td>3</td>
<td>918</td>
<td>70</td>
<td>1313</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">24-03-2025</td>
<td>21:00:00</td>
<td>13178</td>
<td>13178</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>6079</td>
<td>1000</td>
<td>3744</td>
<td>46</td>
<td>0</td>
<td>13</td>
<td>920</td>
<td>64</td>
<td>1312</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">24-03-2025</td>
<td>20:00:00</td>
<td>13128</td>
<td>13128</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>5992</td>
<td>1116</td>
<td>3717</td>
<td>46</td>
<td>0</td>
<td>15</td>
<td>872</td>
<td>60</td>
<td>1310</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">24-03-2025</td>
<td>19:30:00</td>
<td>13340</td>
<td>13340</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>5950</td>
<td>1283</td>
<td>3810</td>
<td>46</td>
<td>0</td>
<td>6</td>
<td>871</td>
<td>68</td>
<td>1306</td>
<td>0</td>
<td>Evening Peak</td>
</tr>
<tr>
<td class="text-nowrap">24-03-2025</td>
<td>19:00:00</td>
<td>13127</td>
<td>13127</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>5824</td>
<td>1308</td>
<td>3689</td>
<td>46</td>
<td>0</td>
<td>8</td>
<td>872</td>
<td>64</td>
<td>1316</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">24-03-2025</td>
<td>18:00:00</td>
<td>13094</td>
<td>13094</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>6051</td>
<td>1294</td>
<td>3531</td>
<td>46</td>
<td>5</td>
<td>13</td>
<td>919</td>
<td>70</td>
<td>1165</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">24-03-2025</td>
<td>17:00:00</td>
<td>12907</td>
<td>12907</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>6096</td>
<td>1072</td>
<td>3466</td>
<td>46</td>
<td>111</td>
<td>18</td>
<td>919</td>
<td>60</td>
<td>1119</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">24-03-2025</td>
<td>16:00:00</td>
<td>12836</td>
<td>12836</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>5951</td>
<td>952</td>
<td>3467</td>
<td>46</td>
<td>291</td>
<td>31</td>
<td>920</td>
<td>62</td>
<td>1116</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">24-03-2025</td>
<td>15:00:00</td>
<td>13013</td>
<td>13013</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>5780</td>
<td>1063</td>
<td>3538</td>
<td>46</td>
<td>463</td>
<td>26</td>
<td>919</td>
<td>62</td>
<td>1116</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">24-03-2025</td>
<td>14:00:00</td>
<td>13015</td>
<td>13015</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>5765</td>
<td>970</td>
<td>3528</td>
<td>46</td>
<td>581</td>
<td>19</td>
<td>920</td>
<td>64</td>
<td>1122</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">24-03-2025</td>
<td>13:00:00</td>
<td>12731</td>
<td>12731</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>5858</td>
<td>755</td>
<td>3356</td>
<td>46</td>
<td>661</td>
<td>11</td>
<td>918</td>
<td>62</td>
<td>1064</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">24-03-2025</td>
<td>12:00:00</td>
<td>12345</td>
<td>12345</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>5888</td>
<td>529</td>
<td>3251</td>
<td>46</td>
<td>686</td>
<td>9</td>
<td>919</td>
<td>58</td>
<td>959</td>
<td>0</td>
<td>Day Peak</td>
</tr>
<tr>
<td class="text-nowrap">24-03-2025</td>
<td>11:00:00</td>
<td>11798</td>
<td>11798</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>5678</td>
<td>506</td>
<td>3001</td>
<td>46</td>
<td>654</td>
<td>18</td>
<td>920</td>
<td>54</td>
<td>921</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">24-03-2025</td>
<td>10:00:00</td>
<td>11572</td>
<td>11572</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>5630</td>
<td>473</td>
<td>2937</td>
<td>46</td>
<td>565</td>
<td>19</td>
<td>916</td>
<td>58</td>
<td>928</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">24-03-2025</td>
<td>09:00:00</td>
<td>11174</td>
<td>11174</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>5628</td>
<td>439</td>
<td>2881</td>
<td>46</td>
<td>422</td>
<td>13</td>
<td>865</td>
<td>52</td>
<td>828</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">24-03-2025</td>
<td>08:00:00</td>
<td>10244</td>
<td>10244</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>5198</td>
<td>372</td>
<td>2635</td>
<td>46</td>
<td>243</td>
<td>15</td>
<td>865</td>
<td>44</td>
<td>826</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">24-03-2025</td>
<td>07:00:00</td>
<td>9615</td>
<td>9615</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>4796</td>
<td>252</td>
<td>2627</td>
<td>46</td>
<td>78</td>
<td>23</td>
<td>919</td>
<td>46</td>
<td>828</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">24-03-2025</td>
<td>06:00:00</td>
<td>9454</td>
<td>9454</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>4749</td>
<td>242</td>
<td>2617</td>
<td>46</td>
<td>0</td>
<td>18</td>
<td>918</td>
<td>42</td>
<td>822</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">24-03-2025</td>
<td>05:00:00</td>
<td>10334</td>
<td>10334</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>5468</td>
<td>279</td>
<td>2725</td>
<td>46</td>
<td>0</td>
<td>15</td>
<td>919</td>
<td>58</td>
<td>824</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">24-03-2025</td>
<td>04:00:00</td>
<td>11355</td>
<td>11355</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>5888</td>
<td>484</td>
<td>3114</td>
<td>46</td>
<td>0</td>
<td>25</td>
<td>920</td>
<td>62</td>
<td>816</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">24-03-2025</td>
<td>03:00:00</td>
<td>11363</td>
<td>11363</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>5706</td>
<td>512</td>
<td>3284</td>
<td>46</td>
<td>0</td>
<td>18</td>
<td>919</td>
<td>60</td>
<td>818</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">24-03-2025</td>
<td>02:00:00</td>
<td>10990</td>
<td>10990</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>5409</td>
<td>438</td>
<td>3269</td>
<td>46</td>
<td>0</td>
<td>20</td>
<td>919</td>
<td>62</td>
<td>827</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">24-03-2025</td>
<td>01:00:00</td>
<td>11456</td>
<td>11456</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>5581</td>
<td>505</td>
<td>3410</td>
<td>46</td>
<td>0</td>
<td>16</td>
<td>914</td>
<td>66</td>
<td>918</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">23-03-2025</td>
<td>24:00:00</td>
<td>12047</td>
<td>12047</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>5922</td>
<td>623</td>
<td>3548</td>
<td>46</td>
<td>0</td>
<td>9</td>
<td>913</td>
<td>70</td>
<td>916</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">23-03-2025</td>
<td>23:00:00</td>
<td>12616</td>
<td>12616</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>6015</td>
<td>725</td>
<td>3779</td>
<td>46</td>
<td>0</td>
<td>7</td>
<td>914</td>
<td>68</td>
<td>1063</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">23-03-2025</td>
<td>22:00:00</td>
<td>12844</td>
<td>12844</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>6153</td>
<td>792</td>
<td>3797</td>
<td>46</td>
<td>0</td>
<td>7</td>
<td>914</td>
<td>66</td>
<td>1069</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">23-03-2025</td>
<td>21:00:00</td>
<td>12962</td>
<td>12962</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>6225</td>
<td>875</td>
<td>3779</td>
<td>46</td>
<td>0</td>
<td>2</td>
<td>907</td>
<td>64</td>
<td>1064</td>
<td>0</td>
<td>Evening Peak</td>
</tr>
<tr>
<td class="text-nowrap">23-03-2025</td>
<td>20:00:00</td>
<td>12922</td>
<td>12922</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>6085</td>
<td>1149</td>
<td>3686</td>
<td>46</td>
<td>0</td>
<td>0</td>
<td>860</td>
<td>70</td>
<td>1026</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">23-03-2025</td>
<td>19:30:00</td>
<td>12859</td>
<td>12859</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>6003</td>
<td>1249</td>
<td>3629</td>
<td>46</td>
<td>0</td>
<td>2</td>
<td>860</td>
<td>70</td>
<td>1000</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">23-03-2025</td>
<td>19:00:00</td>
<td>12872</td>
<td>12872</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>5802</td>
<td>1459</td>
<td>3638</td>
<td>46</td>
<td>0</td>
<td>6</td>
<td>860</td>
<td>68</td>
<td>993</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">23-03-2025</td>
<td>18:00:00</td>
<td>12685</td>
<td>12685</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>6089</td>
<td>1253</td>
<td>3391</td>
<td>46</td>
<td>7</td>
<td>6</td>
<td>913</td>
<td>64</td>
<td>916</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">23-03-2025</td>
<td>17:00:00</td>
<td>12519</td>
<td>12519</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>6054</td>
<td>979</td>
<td>3441</td>
<td>46</td>
<td>99</td>
<td>8</td>
<td>913</td>
<td>60</td>
<td>919</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">23-03-2025</td>
<td>16:00:00</td>
<td>12471</td>
<td>12471</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>6054</td>
<td>742</td>
<td>3459</td>
<td>46</td>
<td>214</td>
<td>17</td>
<td>912</td>
<td>68</td>
<td>959</td>
<td>0</td>
<td></td>
</tr>
<tr>
<td class="text-nowrap">23-03-2025</td>
<td>15:00:00</td>
<td>12578</td>
<td>12578</td>
<!--<td>0.00</td>-->
<td>0</td>
<td>6052</td>
<td>715</td>
<td>3463</td>
<td>46</td>
<td>355</td>
<td>10</td>
<td>913</td>
<td>62</td>
<td>962</td>
<td>0</td>
<td></td>
</tr>
</tbody>
</table>

In [7]:
# Extract headers (first row)
headers = [header.get_text(strip=True) for header in table.find('tr').find_all(['th', 'td'])[:4]]

In [8]:
headers

['Date', 'Time', 'Generation(MW)', 'Demand(MW)']

In [16]:
[header.get_text(strip=True) for header in table.find('tr').find_all(['th', 'td'])[:4]]

['Date', 'Time', 'Generation(MW)', 'Demand(MW)']

In [17]:
table.find_all('tr')

[<tr>
 <th rowspan="2" style="width: 80px;">Date</th>
 <th rowspan="2">Time</th>
 <th rowspan="2">Generation(MW)</th>
 <th rowspan="2">Demand(MW)</th>
 <th rowspan="2">Loadshed</th>
 <th rowspan="2">Gas</th>
 <th rowspan="2">Liquid Fuel</th>
 <th rowspan="2">Coal</th>
 <th rowspan="2">Hydro</th>
 <th rowspan="2">Solar</th>
 <th rowspan="2">Wind</th>
 <th colspan="3" rowspan="1">India</th>
 <th rowspan="2">Nepal</th>
 <th rowspan="2" style="width: 100px;">Remarks</th>
 </tr>,
 <tr>
 <th colspan="1" rowspan="1">Bheramara HVDC</th>
 <th colspan="1" rowspan="1">Tripura</th>
 <th colspan="1" rowspan="1">Adani</th>
 </tr>,
 <tr>
 <td class="text-nowrap">25-03-2025</td>
 <td>15:00:00</td>
 <td>13302</td>
 <td>13302</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>5837</td>
 <td>1181</td>
 <td>3478</td>
 <td>46</td>
 <td>467</td>
 <td>40</td>
 <td>918</td>
 <td>72</td>
 <td>1263</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">25-03-2025</td>
 <td>14:00:00</td>
 <td>13253</td>
 <td>13253</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>5909</td>
 <td>938</td>
 <td>3480</td>
 <td>46</td>
 <td>583</td>
 <td>28</td>
 <td>918</td>
 <td>82</td>
 <td>1269</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">25-03-2025</td>
 <td>13:00:00</td>
 <td>13048</td>
 <td>13048</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>5949</td>
 <td>744</td>
 <td>3420</td>
 <td>46</td>
 <td>658</td>
 <td>27</td>
 <td>919</td>
 <td>72</td>
 <td>1213</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">25-03-2025</td>
 <td>12:00:00</td>
 <td>12734</td>
 <td>12734</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>5959</td>
 <td>531</td>
 <td>3408</td>
 <td>46</td>
 <td>682</td>
 <td>6</td>
 <td>919</td>
 <td>68</td>
 <td>1115</td>
 <td>0</td>
 <td>Day Peak</td>
 </tr>,
 <tr>
 <td class="text-nowrap">25-03-2025</td>
 <td>11:00:00</td>
 <td>12251</td>
 <td>12251</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>5965</td>
 <td>449</td>
 <td>3124</td>
 <td>46</td>
 <td>659</td>
 <td>12</td>
 <td>919</td>
 <td>64</td>
 <td>1013</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">25-03-2025</td>
 <td>10:00:00</td>
 <td>11940</td>
 <td>11940</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>6077</td>
 <td>410</td>
 <td>2921</td>
 <td>46</td>
 <td>577</td>
 <td>9</td>
 <td>919</td>
 <td>58</td>
 <td>923</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">25-03-2025</td>
 <td>09:00:00</td>
 <td>11375</td>
 <td>11375</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>6078</td>
 <td>376</td>
 <td>2710</td>
 <td>46</td>
 <td>414</td>
 <td>6</td>
 <td>870</td>
 <td>58</td>
 <td>817</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">25-03-2025</td>
 <td>08:00:00</td>
 <td>10826</td>
 <td>10826</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>5949</td>
 <td>314</td>
 <td>2521</td>
 <td>46</td>
 <td>247</td>
 <td>8</td>
 <td>870</td>
 <td>54</td>
 <td>817</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">25-03-2025</td>
 <td>07:00:00</td>
 <td>10066</td>
 <td>10066</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>5423</td>
 <td>229</td>
 <td>2496</td>
 <td>46</td>
 <td>77</td>
 <td>12</td>
 <td>919</td>
 <td>40</td>
 <td>824</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">25-03-2025</td>
 <td>06:00:00</td>
 <td>9802</td>
 <td>9802</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>5182</td>
 <td>215</td>
 <td>2542</td>
 <td>46</td>
 <td>0</td>
 <td>16</td>
 <td>920</td>
 <td>50</td>
 <td>831</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">25-03-2025</td>
 <td>05:00:00</td>
 <td>10496</td>
 <td>10496</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>5623</td>
 <td>266</td>
 <td>2735</td>
 <td>46</td>
 <td>0</td>
 <td>19</td>
 <td>919</td>
 <td>56</td>
 <td>832</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">25-03-2025</td>
 <td>04:00:00</td>
 <td>11745</td>
 <td>11745</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>5760</td>
 <td>605</td>
 <td>3402</td>
 <td>46</td>
 <td>0</td>
 <td>19</td>
 <td>919</td>
 <td>64</td>
 <td>930</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">25-03-2025</td>
 <td>03:00:00</td>
 <td>11754</td>
 <td>11754</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>5967</td>
 <td>589</td>
 <td>3124</td>
 <td>46</td>
 <td>0</td>
 <td>29</td>
 <td>919</td>
 <td>62</td>
 <td>1018</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">25-03-2025</td>
 <td>02:00:00</td>
 <td>11393</td>
 <td>11393</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>5667</td>
 <td>550</td>
 <td>3087</td>
 <td>46</td>
 <td>0</td>
 <td>37</td>
 <td>919</td>
 <td>64</td>
 <td>1023</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">25-03-2025</td>
 <td>01:00:00</td>
 <td>11831</td>
 <td>11831</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>5908</td>
 <td>596</td>
 <td>3219</td>
 <td>46</td>
 <td>0</td>
 <td>24</td>
 <td>919</td>
 <td>62</td>
 <td>1057</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">24-03-2025</td>
 <td>24:00:00</td>
 <td>12305</td>
 <td>12305</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>6034</td>
 <td>681</td>
 <td>3380</td>
 <td>46</td>
 <td>0</td>
 <td>13</td>
 <td>919</td>
 <td>68</td>
 <td>1164</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">24-03-2025</td>
 <td>23:00:00</td>
 <td>12741</td>
 <td>12741</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>6068</td>
 <td>788</td>
 <td>3588</td>
 <td>46</td>
 <td>0</td>
 <td>1</td>
 <td>919</td>
 <td>70</td>
 <td>1261</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">24-03-2025</td>
 <td>22:00:00</td>
 <td>13076</td>
 <td>13076</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>6013</td>
 <td>959</td>
 <td>3754</td>
 <td>46</td>
 <td>0</td>
 <td>3</td>
 <td>918</td>
 <td>70</td>
 <td>1313</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">24-03-2025</td>
 <td>21:00:00</td>
 <td>13178</td>
 <td>13178</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>6079</td>
 <td>1000</td>
 <td>3744</td>
 <td>46</td>
 <td>0</td>
 <td>13</td>
 <td>920</td>
 <td>64</td>
 <td>1312</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">24-03-2025</td>
 <td>20:00:00</td>
 <td>13128</td>
 <td>13128</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>5992</td>
 <td>1116</td>
 <td>3717</td>
 <td>46</td>
 <td>0</td>
 <td>15</td>
 <td>872</td>
 <td>60</td>
 <td>1310</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">24-03-2025</td>
 <td>19:30:00</td>
 <td>13340</td>
 <td>13340</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>5950</td>
 <td>1283</td>
 <td>3810</td>
 <td>46</td>
 <td>0</td>
 <td>6</td>
 <td>871</td>
 <td>68</td>
 <td>1306</td>
 <td>0</td>
 <td>Evening Peak</td>
 </tr>,
 <tr>
 <td class="text-nowrap">24-03-2025</td>
 <td>19:00:00</td>
 <td>13127</td>
 <td>13127</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>5824</td>
 <td>1308</td>
 <td>3689</td>
 <td>46</td>
 <td>0</td>
 <td>8</td>
 <td>872</td>
 <td>64</td>
 <td>1316</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">24-03-2025</td>
 <td>18:00:00</td>
 <td>13094</td>
 <td>13094</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>6051</td>
 <td>1294</td>
 <td>3531</td>
 <td>46</td>
 <td>5</td>
 <td>13</td>
 <td>919</td>
 <td>70</td>
 <td>1165</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">24-03-2025</td>
 <td>17:00:00</td>
 <td>12907</td>
 <td>12907</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>6096</td>
 <td>1072</td>
 <td>3466</td>
 <td>46</td>
 <td>111</td>
 <td>18</td>
 <td>919</td>
 <td>60</td>
 <td>1119</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">24-03-2025</td>
 <td>16:00:00</td>
 <td>12836</td>
 <td>12836</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>5951</td>
 <td>952</td>
 <td>3467</td>
 <td>46</td>
 <td>291</td>
 <td>31</td>
 <td>920</td>
 <td>62</td>
 <td>1116</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">24-03-2025</td>
 <td>15:00:00</td>
 <td>13013</td>
 <td>13013</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>5780</td>
 <td>1063</td>
 <td>3538</td>
 <td>46</td>
 <td>463</td>
 <td>26</td>
 <td>919</td>
 <td>62</td>
 <td>1116</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">24-03-2025</td>
 <td>14:00:00</td>
 <td>13015</td>
 <td>13015</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>5765</td>
 <td>970</td>
 <td>3528</td>
 <td>46</td>
 <td>581</td>
 <td>19</td>
 <td>920</td>
 <td>64</td>
 <td>1122</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">24-03-2025</td>
 <td>13:00:00</td>
 <td>12731</td>
 <td>12731</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>5858</td>
 <td>755</td>
 <td>3356</td>
 <td>46</td>
 <td>661</td>
 <td>11</td>
 <td>918</td>
 <td>62</td>
 <td>1064</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">24-03-2025</td>
 <td>12:00:00</td>
 <td>12345</td>
 <td>12345</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>5888</td>
 <td>529</td>
 <td>3251</td>
 <td>46</td>
 <td>686</td>
 <td>9</td>
 <td>919</td>
 <td>58</td>
 <td>959</td>
 <td>0</td>
 <td>Day Peak</td>
 </tr>,
 <tr>
 <td class="text-nowrap">24-03-2025</td>
 <td>11:00:00</td>
 <td>11798</td>
 <td>11798</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>5678</td>
 <td>506</td>
 <td>3001</td>
 <td>46</td>
 <td>654</td>
 <td>18</td>
 <td>920</td>
 <td>54</td>
 <td>921</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">24-03-2025</td>
 <td>10:00:00</td>
 <td>11572</td>
 <td>11572</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>5630</td>
 <td>473</td>
 <td>2937</td>
 <td>46</td>
 <td>565</td>
 <td>19</td>
 <td>916</td>
 <td>58</td>
 <td>928</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">24-03-2025</td>
 <td>09:00:00</td>
 <td>11174</td>
 <td>11174</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>5628</td>
 <td>439</td>
 <td>2881</td>
 <td>46</td>
 <td>422</td>
 <td>13</td>
 <td>865</td>
 <td>52</td>
 <td>828</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">24-03-2025</td>
 <td>08:00:00</td>
 <td>10244</td>
 <td>10244</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>5198</td>
 <td>372</td>
 <td>2635</td>
 <td>46</td>
 <td>243</td>
 <td>15</td>
 <td>865</td>
 <td>44</td>
 <td>826</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">24-03-2025</td>
 <td>07:00:00</td>
 <td>9615</td>
 <td>9615</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>4796</td>
 <td>252</td>
 <td>2627</td>
 <td>46</td>
 <td>78</td>
 <td>23</td>
 <td>919</td>
 <td>46</td>
 <td>828</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">24-03-2025</td>
 <td>06:00:00</td>
 <td>9454</td>
 <td>9454</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>4749</td>
 <td>242</td>
 <td>2617</td>
 <td>46</td>
 <td>0</td>
 <td>18</td>
 <td>918</td>
 <td>42</td>
 <td>822</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">24-03-2025</td>
 <td>05:00:00</td>
 <td>10334</td>
 <td>10334</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>5468</td>
 <td>279</td>
 <td>2725</td>
 <td>46</td>
 <td>0</td>
 <td>15</td>
 <td>919</td>
 <td>58</td>
 <td>824</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">24-03-2025</td>
 <td>04:00:00</td>
 <td>11355</td>
 <td>11355</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>5888</td>
 <td>484</td>
 <td>3114</td>
 <td>46</td>
 <td>0</td>
 <td>25</td>
 <td>920</td>
 <td>62</td>
 <td>816</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">24-03-2025</td>
 <td>03:00:00</td>
 <td>11363</td>
 <td>11363</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>5706</td>
 <td>512</td>
 <td>3284</td>
 <td>46</td>
 <td>0</td>
 <td>18</td>
 <td>919</td>
 <td>60</td>
 <td>818</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">24-03-2025</td>
 <td>02:00:00</td>
 <td>10990</td>
 <td>10990</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>5409</td>
 <td>438</td>
 <td>3269</td>
 <td>46</td>
 <td>0</td>
 <td>20</td>
 <td>919</td>
 <td>62</td>
 <td>827</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">24-03-2025</td>
 <td>01:00:00</td>
 <td>11456</td>
 <td>11456</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>5581</td>
 <td>505</td>
 <td>3410</td>
 <td>46</td>
 <td>0</td>
 <td>16</td>
 <td>914</td>
 <td>66</td>
 <td>918</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">23-03-2025</td>
 <td>24:00:00</td>
 <td>12047</td>
 <td>12047</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>5922</td>
 <td>623</td>
 <td>3548</td>
 <td>46</td>
 <td>0</td>
 <td>9</td>
 <td>913</td>
 <td>70</td>
 <td>916</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">23-03-2025</td>
 <td>23:00:00</td>
 <td>12616</td>
 <td>12616</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>6015</td>
 <td>725</td>
 <td>3779</td>
 <td>46</td>
 <td>0</td>
 <td>7</td>
 <td>914</td>
 <td>68</td>
 <td>1063</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">23-03-2025</td>
 <td>22:00:00</td>
 <td>12844</td>
 <td>12844</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>6153</td>
 <td>792</td>
 <td>3797</td>
 <td>46</td>
 <td>0</td>
 <td>7</td>
 <td>914</td>
 <td>66</td>
 <td>1069</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">23-03-2025</td>
 <td>21:00:00</td>
 <td>12962</td>
 <td>12962</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>6225</td>
 <td>875</td>
 <td>3779</td>
 <td>46</td>
 <td>0</td>
 <td>2</td>
 <td>907</td>
 <td>64</td>
 <td>1064</td>
 <td>0</td>
 <td>Evening Peak</td>
 </tr>,
 <tr>
 <td class="text-nowrap">23-03-2025</td>
 <td>20:00:00</td>
 <td>12922</td>
 <td>12922</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>6085</td>
 <td>1149</td>
 <td>3686</td>
 <td>46</td>
 <td>0</td>
 <td>0</td>
 <td>860</td>
 <td>70</td>
 <td>1026</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">23-03-2025</td>
 <td>19:30:00</td>
 <td>12859</td>
 <td>12859</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>6003</td>
 <td>1249</td>
 <td>3629</td>
 <td>46</td>
 <td>0</td>
 <td>2</td>
 <td>860</td>
 <td>70</td>
 <td>1000</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">23-03-2025</td>
 <td>19:00:00</td>
 <td>12872</td>
 <td>12872</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>5802</td>
 <td>1459</td>
 <td>3638</td>
 <td>46</td>
 <td>0</td>
 <td>6</td>
 <td>860</td>
 <td>68</td>
 <td>993</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">23-03-2025</td>
 <td>18:00:00</td>
 <td>12685</td>
 <td>12685</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>6089</td>
 <td>1253</td>
 <td>3391</td>
 <td>46</td>
 <td>7</td>
 <td>6</td>
 <td>913</td>
 <td>64</td>
 <td>916</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">23-03-2025</td>
 <td>17:00:00</td>
 <td>12519</td>
 <td>12519</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>6054</td>
 <td>979</td>
 <td>3441</td>
 <td>46</td>
 <td>99</td>
 <td>8</td>
 <td>913</td>
 <td>60</td>
 <td>919</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">23-03-2025</td>
 <td>16:00:00</td>
 <td>12471</td>
 <td>12471</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>6054</td>
 <td>742</td>
 <td>3459</td>
 <td>46</td>
 <td>214</td>
 <td>17</td>
 <td>912</td>
 <td>68</td>
 <td>959</td>
 <td>0</td>
 <td></td>
 </tr>,
 <tr>
 <td class="text-nowrap">23-03-2025</td>
 <td>15:00:00</td>
 <td>12578</td>
 <td>12578</td>
 <!--<td>0.00</td>-->
 <td>0</td>
 <td>6052</td>
 <td>715</td>
 <td>3463</td>
 <td>46</td>
 <td>355</td>
 <td>10</td>
 <td>913</td>
 <td>62</td>
 <td>962</td>
 <td>0</td>
 <td></td>
 </tr>]

In [18]:
# Extract data rows (skipping the header row)
data = []
for row in table.find_all('tr')[2:]:
    columns = row.find_all(['td', 'th'])
    # Get first 4 columns and strip whitespace
    row_data = [col.get_text(strip=True) for col in columns[:4]]
    data.append(row_data)

In [19]:
# Print results
print(headers)
for row in data:
    print(row)

['Date', 'Time', 'Generation(MW)', 'Demand(MW)']
['25-03-2025', '15:00:00', '13302', '13302']
['25-03-2025', '14:00:00', '13253', '13253']
['25-03-2025', '13:00:00', '13048', '13048']
['25-03-2025', '12:00:00', '12734', '12734']
['25-03-2025', '11:00:00', '12251', '12251']
['25-03-2025', '10:00:00', '11940', '11940']
['25-03-2025', '09:00:00', '11375', '11375']
['25-03-2025', '08:00:00', '10826', '10826']
['25-03-2025', '07:00:00', '10066', '10066']
['25-03-2025', '06:00:00', '9802', '9802']
['25-03-2025', '05:00:00', '10496', '10496']
['25-03-2025', '04:00:00', '11745', '11745']
['25-03-2025', '03:00:00', '11754', '11754']
['25-03-2025', '02:00:00', '11393', '11393']
['25-03-2025', '01:00:00', '11831', '11831']
['24-03-2025', '24:00:00', '12305', '12305']
['24-03-2025', '23:00:00', '12741', '12741']
['24-03-2025', '22:00:00', '13076', '13076']
['24-03-2025', '21:00:00', '13178', '13178']
['24-03-2025', '20:00:00', '13128', '13128']
['24-03-2025', '19:30:00', '13340', '13340']
['24-03-2025', '19:00:00', '13127', '13127']
['24-03-2025', '18:00:00', '13094', '13094']
['24-03-2025', '17:00:00', '12907', '12907']
['24-03-2025', '16:00:00', '12836', '12836']
['24-03-2025', '15:00:00', '13013', '13013']
['24-03-2025', '14:00:00', '13015', '13015']
['24-03-2025', '13:00:00', '12731', '12731']
['24-03-2025', '12:00:00', '12345', '12345']
['24-03-2025', '11:00:00', '11798', '11798']
['24-03-2025', '10:00:00', '11572', '11572']
['24-03-2025', '09:00:00', '11174', '11174']
['24-03-2025', '08:00:00', '10244', '10244']
['24-03-2025', '07:00:00', '9615', '9615']
['24-03-2025', '06:00:00', '9454', '9454']
['24-03-2025', '05:00:00', '10334', '10334']
['24-03-2025', '04:00:00', '11355', '11355']
['24-03-2025', '03:00:00', '11363', '11363']
['24-03-2025', '02:00:00', '10990', '10990']
['24-03-2025', '01:00:00', '11456', '11456']
['23-03-2025', '24:00:00', '12047', '12047']
['23-03-2025', '23:00:00', '12616', '12616']
['23-03-2025', '22:00:00', '12844', '12844']
['23-03-2025', '21:00:00', '12962', '12962']
['23-03-2025', '20:00:00', '12922', '12922']
['23-03-2025', '19:30:00', '12859', '12859']
['23-03-2025', '19:00:00', '12872', '12872']
['23-03-2025', '18:00:00', '12685', '12685']
['23-03-2025', '17:00:00', '12519', '12519']
['23-03-2025', '16:00:00', '12471', '12471']
['23-03-2025', '15:00:00', '12578', '12578']

In [22]:
filename = 'output.csv'
with open(filename, 'w', newline='', encoding='utf-8') as csvfile:
    writer = csv.writer(csvfile)
    
    # Write header
    writer.writerow(headers)
    
    # Write data rows
    writer.writerows(data)

print(f"Data successfully saved to {filename}")

Data successfully saved to output.csv

In [23]:
import pandas as pd

In [25]:
df = pd.read_csv('./output.csv')

In [27]:
df.shape

(51, 4)

In [28]:
df.head()

         Date      Time  Generation(MW)  Demand(MW)
0  25-03-2025  15:00:00           13302       13302
1  25-03-2025  14:00:00           13253       13253
2  25-03-2025  13:00:00           13048       13048
3  25-03-2025  12:00:00           12734       12734
4  25-03-2025  11:00:00           12251       12251

In [36]:
import requests
from bs4 import BeautifulSoup
import csv
import urllib3
import time

# Disable SSL warnings (temporary solution)
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# Configure settings
base_url = "https://erp.powergrid.gov.bd/web/generations/view_generations"
total_pages = 1776
output_file = "all_pages_data.csv"
delay_between_requests = 1  # seconds to wait between requests

# Create session for connection pooling
session = requests.Session()

# Set common headers
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'
}

def scrape_page(page_number):
    """Scrape data from a single page"""
    try:
        # Add pagination parameter (adjust if needed - check website's actual pagination pattern)
        params = {'page': page_number}
        
        response = session.get(
            base_url,
            params=params,
            headers=headers,
            verify=False,
            timeout=30
        )
        response.raise_for_status()
        
        soup = BeautifulSoup(response.content, 'html.parser')
        table = soup.find('table')
        
        if not table:
            print(f"No table found on page {page_number}")
            return None
            
        # Extract data
        page_data = []
        for row in table.find_all('tr')[2:]:  # Skip header row
            cols = row.find_all(['td', 'th'])[:4]
            page_data.append([col.get_text(strip=True) for col in cols])
            
        return page_data
        
    except Exception as e:
        print(f"Error on page {page_number}: {str(e)}")
        return None

# Initialize CSV with headers
with open(output_file, 'w', newline='', encoding='utf-8') as csvfile:
    writer = csv.writer(csvfile)
    
    # Get headers from first page
    first_page_data = scrape_page(1)
    if first_page_data:
        header_row = [h.get_text(strip=True) for h in table.find('tr').find_all(['th', 'td'])[:4]]
        writer.writerow(header_row)
        writer.writerows(first_page_data)

# Scrape remaining pages
for page in range(2, total_pages + 1):
    try:
        page_data = scrape_page(page)
        if page_data:
            with open(output_file, 'a', newline='', encoding='utf-8') as csvfile:
                writer = csv.writer(csvfile)
                writer.writerows(page_data)
            print(f"Page {page}/{total_pages} scraped successfully")
            
        # Be polite - add delay
        time.sleep(delay_between_requests)
        
    except KeyboardInterrupt:
        print("Scraping interrupted by user")
        break
    except Exception as e:
        print(f"Critical error on page {page}: {str(e)}")
        continue

print(f"Scraping completed. Data saved to {output_file}")

Page 2/1776 scraped successfully
Page 3/1776 scraped successfully
Page 4/1776 scraped successfully
Page 5/1776 scraped successfully
Page 6/1776 scraped successfully
Page 7/1776 scraped successfully
Page 8/1776 scraped successfully
Page 9/1776 scraped successfully
Page 10/1776 scraped successfully
Page 11/1776 scraped successfully
Page 12/1776 scraped successfully
Page 13/1776 scraped successfully
Page 14/1776 scraped successfully
Page 15/1776 scraped successfully
Page 16/1776 scraped successfully
Page 17/1776 scraped successfully
Page 18/1776 scraped successfully
Page 19/1776 scraped successfully
Page 20/1776 scraped successfully
Page 21/1776 scraped successfully
Page 22/1776 scraped successfully
Page 23/1776 scraped successfully
Page 24/1776 scraped successfully
Page 25/1776 scraped successfully
Page 26/1776 scraped successfully
Page 27/1776 scraped successfully
Page 28/1776 scraped successfully
Page 29/1776 scraped successfully
Page 30/1776 scraped successfully
Page 31/1776 scraped successfully
Page 32/1776 scraped successfully
Page 33/1776 scraped successfully
Page 34/1776 scraped successfully
Page 35/1776 scraped successfully
Page 36/1776 scraped successfully
Page 37/1776 scraped successfully
Page 38/1776 scraped successfully
Page 39/1776 scraped successfully
Page 40/1776 scraped successfully
Page 41/1776 scraped successfully
Page 42/1776 scraped successfully
Page 43/1776 scraped successfully
Page 44/1776 scraped successfully
Page 45/1776 scraped successfully
Page 46/1776 scraped successfully
Page 47/1776 scraped successfully
Page 48/1776 scraped successfully
Page 49/1776 scraped successfully
Page 50/1776 scraped successfully
Page 51/1776 scraped successfully
Page 52/1776 scraped successfully
Page 53/1776 scraped successfully
Page 54/1776 scraped successfully
Page 55/1776 scraped successfully
Page 56/1776 scraped successfully
Page 57/1776 scraped successfully
Page 58/1776 scraped successfully
Page 59/1776 scraped successfully
Page 60/1776 scraped successfully
Page 61/1776 scraped successfully
Page 62/1776 scraped successfully
Page 63/1776 scraped successfully
Page 64/1776 scraped successfully
Page 65/1776 scraped successfully
Page 66/1776 scraped successfully
Page 67/1776 scraped successfully
Page 68/1776 scraped successfully
Page 69/1776 scraped successfully
Page 70/1776 scraped successfully
Page 71/1776 scraped successfully
Page 72/1776 scraped successfully
Page 73/1776 scraped successfully
Page 74/1776 scraped successfully
Page 75/1776 scraped successfully
Page 76/1776 scraped successfully
Page 77/1776 scraped successfully
Page 78/1776 scraped successfully
Page 79/1776 scraped successfully
Page 80/1776 scraped successfully
Page 81/1776 scraped successfully
Page 82/1776 scraped successfully
Page 83/1776 scraped successfully
Page 84/1776 scraped successfully
Page 85/1776 scraped successfully
Page 86/1776 scraped successfully
Page 87/1776 scraped successfully
Page 88/1776 scraped successfully
Page 89/1776 scraped successfully
Page 90/1776 scraped successfully
Page 91/1776 scraped successfully
Page 92/1776 scraped successfully
Page 93/1776 scraped successfully
Page 94/1776 scraped successfully
Page 95/1776 scraped successfully
Page 96/1776 scraped successfully
Page 97/1776 scraped successfully
Page 98/1776 scraped successfully
Page 99/1776 scraped successfully
Page 100/1776 scraped successfully
Page 101/1776 scraped successfully
Page 102/1776 scraped successfully
Page 103/1776 scraped successfully
Page 104/1776 scraped successfully
Page 105/1776 scraped successfully
Page 106/1776 scraped successfully
Page 107/1776 scraped successfully
Page 108/1776 scraped successfully
Page 109/1776 scraped successfully
Page 110/1776 scraped successfully
Page 111/1776 scraped successfully
Page 112/1776 scraped successfully
Page 113/1776 scraped successfully
Page 114/1776 scraped successfully
Page 115/1776 scraped successfully
Page 116/1776 scraped successfully
Page 117/1776 scraped successfully
Page 118/1776 scraped successfully
Page 119/1776 scraped successfully
Page 120/1776 scraped successfully
Page 121/1776 scraped successfully
Page 122/1776 scraped successfully
Page 123/1776 scraped successfully
Page 124/1776 scraped successfully
Page 125/1776 scraped successfully
Page 126/1776 scraped successfully
Page 127/1776 scraped successfully
Page 128/1776 scraped successfully
Page 129/1776 scraped successfully
Page 130/1776 scraped successfully
Page 131/1776 scraped successfully
Page 132/1776 scraped successfully
Page 133/1776 scraped successfully
Page 134/1776 scraped successfully
Page 135/1776 scraped successfully
Page 136/1776 scraped successfully
Page 137/1776 scraped successfully
Page 138/1776 scraped successfully
Page 139/1776 scraped successfully
Page 140/1776 scraped successfully
Page 141/1776 scraped successfully
Page 142/1776 scraped successfully
Page 143/1776 scraped successfully
Page 144/1776 scraped successfully
Page 145/1776 scraped successfully
Page 146/1776 scraped successfully
Page 147/1776 scraped successfully
Page 148/1776 scraped successfully
Page 149/1776 scraped successfully
Page 150/1776 scraped successfully
Page 151/1776 scraped successfully
Page 152/1776 scraped successfully
Page 153/1776 scraped successfully
Page 154/1776 scraped successfully
Page 155/1776 scraped successfully
Page 156/1776 scraped successfully
Page 157/1776 scraped successfully
Page 158/1776 scraped successfully
Page 159/1776 scraped successfully
Page 160/1776 scraped successfully
Page 161/1776 scraped successfully
Page 162/1776 scraped successfully
Page 163/1776 scraped successfully
Page 164/1776 scraped successfully
Page 165/1776 scraped successfully
Page 166/1776 scraped successfully
Page 167/1776 scraped successfully
Page 168/1776 scraped successfully
Page 169/1776 scraped successfully
Page 170/1776 scraped successfully
Page 171/1776 scraped successfully
Page 172/1776 scraped successfully
Page 173/1776 scraped successfully
Page 174/1776 scraped successfully
Page 175/1776 scraped successfully
Page 176/1776 scraped successfully
Page 177/1776 scraped successfully
Page 178/1776 scraped successfully
Page 179/1776 scraped successfully
Page 180/1776 scraped successfully
Page 181/1776 scraped successfully
Page 182/1776 scraped successfully
Page 183/1776 scraped successfully
Page 184/1776 scraped successfully
Page 185/1776 scraped successfully
Page 186/1776 scraped successfully
Page 187/1776 scraped successfully
Page 188/1776 scraped successfully
Page 189/1776 scraped successfully
Page 190/1776 scraped successfully
Page 191/1776 scraped successfully
Page 192/1776 scraped successfully
Page 193/1776 scraped successfully
Page 194/1776 scraped successfully
Page 195/1776 scraped successfully
Page 196/1776 scraped successfully
Page 197/1776 scraped successfully
Page 198/1776 scraped successfully
Page 199/1776 scraped successfully
Page 200/1776 scraped successfully
Page 201/1776 scraped successfully
Page 202/1776 scraped successfully
Page 203/1776 scraped successfully
Page 204/1776 scraped successfully
Page 205/1776 scraped successfully
Page 206/1776 scraped successfully
Page 207/1776 scraped successfully
Page 208/1776 scraped successfully
Page 209/1776 scraped successfully
Page 210/1776 scraped successfully
Page 211/1776 scraped successfully
Page 212/1776 scraped successfully
Page 213/1776 scraped successfully
Page 214/1776 scraped successfully
Page 215/1776 scraped successfully
Page 216/1776 scraped successfully
Page 217/1776 scraped successfully
Page 218/1776 scraped successfully
Page 219/1776 scraped successfully
Page 220/1776 scraped successfully
Page 221/1776 scraped successfully
Page 222/1776 scraped successfully
Page 223/1776 scraped successfully
Page 224/1776 scraped successfully
Page 225/1776 scraped successfully
Page 226/1776 scraped successfully
Page 227/1776 scraped successfully
Page 228/1776 scraped successfully
Page 229/1776 scraped successfully
Page 230/1776 scraped successfully
Page 231/1776 scraped successfully
Page 232/1776 scraped successfully
Page 233/1776 scraped successfully
Page 234/1776 scraped successfully
Page 235/1776 scraped successfully
Page 236/1776 scraped successfully
Page 237/1776 scraped successfully
Page 238/1776 scraped successfully
Page 239/1776 scraped successfully
Page 240/1776 scraped successfully
Page 241/1776 scraped successfully
Page 242/1776 scraped successfully
Page 243/1776 scraped successfully
Page 244/1776 scraped successfully
Page 245/1776 scraped successfully
Page 246/1776 scraped successfully
Page 247/1776 scraped successfully
Page 248/1776 scraped successfully
Page 249/1776 scraped successfully
Page 250/1776 scraped successfully
Page 251/1776 scraped successfully
Page 252/1776 scraped successfully
Page 253/1776 scraped successfully
Page 254/1776 scraped successfully
Page 255/1776 scraped successfully
Page 256/1776 scraped successfully
Page 257/1776 scraped successfully
Page 258/1776 scraped successfully
Page 259/1776 scraped successfully
Page 260/1776 scraped successfully
Page 261/1776 scraped successfully
Page 262/1776 scraped successfully
Page 263/1776 scraped successfully
Page 264/1776 scraped successfully
Page 265/1776 scraped successfully
Page 266/1776 scraped successfully
Page 267/1776 scraped successfully
Page 268/1776 scraped successfully
Page 269/1776 scraped successfully
Page 270/1776 scraped successfully
Page 271/1776 scraped successfully
Page 272/1776 scraped successfully
Page 273/1776 scraped successfully
Page 274/1776 scraped successfully
Page 275/1776 scraped successfully
Page 276/1776 scraped successfully
Page 277/1776 scraped successfully
Page 278/1776 scraped successfully
Page 279/1776 scraped successfully
Page 280/1776 scraped successfully
Page 281/1776 scraped successfully
Page 282/1776 scraped successfully
Page 283/1776 scraped successfully
Page 284/1776 scraped successfully
Page 285/1776 scraped successfully
Page 286/1776 scraped successfully
Page 287/1776 scraped successfully
Page 288/1776 scraped successfully
Page 289/1776 scraped successfully
Page 290/1776 scraped successfully
Page 291/1776 scraped successfully
Page 292/1776 scraped successfully
Page 293/1776 scraped successfully
Page 294/1776 scraped successfully
Page 295/1776 scraped successfully
Page 296/1776 scraped successfully
Page 297/1776 scraped successfully
Page 298/1776 scraped successfully
Page 299/1776 scraped successfully
Page 300/1776 scraped successfully
Page 301/1776 scraped successfully
Page 302/1776 scraped successfully
Page 303/1776 scraped successfully
Page 304/1776 scraped successfully
Page 305/1776 scraped successfully
Page 306/1776 scraped successfully
Page 307/1776 scraped successfully
Page 308/1776 scraped successfully
Page 309/1776 scraped successfully
Page 310/1776 scraped successfully
Page 311/1776 scraped successfully
Page 312/1776 scraped successfully
Page 313/1776 scraped successfully
Page 314/1776 scraped successfully
Page 315/1776 scraped successfully
Page 316/1776 scraped successfully
Page 317/1776 scraped successfully
Page 318/1776 scraped successfully
Page 319/1776 scraped successfully
Page 320/1776 scraped successfully
Page 321/1776 scraped successfully
Page 322/1776 scraped successfully
Page 323/1776 scraped successfully
Page 324/1776 scraped successfully
Page 325/1776 scraped successfully
Page 326/1776 scraped successfully
Page 327/1776 scraped successfully
Page 328/1776 scraped successfully
Page 329/1776 scraped successfully
Page 330/1776 scraped successfully
Page 331/1776 scraped successfully
Page 332/1776 scraped successfully
Page 333/1776 scraped successfully
Page 334/1776 scraped successfully
Page 335/1776 scraped successfully
Page 336/1776 scraped successfully
Page 337/1776 scraped successfully
Page 338/1776 scraped successfully
Page 339/1776 scraped successfully
Page 340/1776 scraped successfully
Page 341/1776 scraped successfully
Page 342/1776 scraped successfully
Page 343/1776 scraped successfully
Page 344/1776 scraped successfully
Page 345/1776 scraped successfully
Page 346/1776 scraped successfully
Page 347/1776 scraped successfully
Page 348/1776 scraped successfully
Page 349/1776 scraped successfully
Page 350/1776 scraped successfully
Page 351/1776 scraped successfully
Page 352/1776 scraped successfully
Page 353/1776 scraped successfully
Page 354/1776 scraped successfully
Page 355/1776 scraped successfully
Page 356/1776 scraped successfully
Page 357/1776 scraped successfully
Page 358/1776 scraped successfully
Page 359/1776 scraped successfully
Page 360/1776 scraped successfully
Page 361/1776 scraped successfully
Page 362/1776 scraped successfully
Page 363/1776 scraped successfully
Page 364/1776 scraped successfully
Page 365/1776 scraped successfully
Page 366/1776 scraped successfully
Page 367/1776 scraped successfully
Page 368/1776 scraped successfully
Page 369/1776 scraped successfully
Page 370/1776 scraped successfully
Page 371/1776 scraped successfully
Page 372/1776 scraped successfully
Page 373/1776 scraped successfully
Page 374/1776 scraped successfully
Page 375/1776 scraped successfully
Page 376/1776 scraped successfully
Page 377/1776 scraped successfully
Page 378/1776 scraped successfully
Page 379/1776 scraped successfully
Page 380/1776 scraped successfully
Page 381/1776 scraped successfully
Page 382/1776 scraped successfully
Page 383/1776 scraped successfully
Page 384/1776 scraped successfully
Page 385/1776 scraped successfully
Page 386/1776 scraped successfully
Page 387/1776 scraped successfully
Page 388/1776 scraped successfully
Page 389/1776 scraped successfully
Page 390/1776 scraped successfully
Page 391/1776 scraped successfully
Page 392/1776 scraped successfully
Page 393/1776 scraped successfully
Page 394/1776 scraped successfully
Page 395/1776 scraped successfully
Page 396/1776 scraped successfully
Page 397/1776 scraped successfully
Page 398/1776 scraped successfully
Page 399/1776 scraped successfully
Page 400/1776 scraped successfully
Page 401/1776 scraped successfully
Page 402/1776 scraped successfully
Page 403/1776 scraped successfully
Page 404/1776 scraped successfully
Page 405/1776 scraped successfully
Page 406/1776 scraped successfully
Page 407/1776 scraped successfully
Page 408/1776 scraped successfully
Page 409/1776 scraped successfully
Page 410/1776 scraped successfully
Page 411/1776 scraped successfully
Page 412/1776 scraped successfully
Page 413/1776 scraped successfully
Page 414/1776 scraped successfully
Page 415/1776 scraped successfully
Page 416/1776 scraped successfully
Page 417/1776 scraped successfully
Page 418/1776 scraped successfully
Page 419/1776 scraped successfully
Page 420/1776 scraped successfully
Page 421/1776 scraped successfully
Page 422/1776 scraped successfully
Page 423/1776 scraped successfully
Page 424/1776 scraped successfully
Page 425/1776 scraped successfully
Page 426/1776 scraped successfully
Page 427/1776 scraped successfully
Page 428/1776 scraped successfully
Page 429/1776 scraped successfully
Page 430/1776 scraped successfully
Page 431/1776 scraped successfully
Page 432/1776 scraped successfully
Page 433/1776 scraped successfully
Page 434/1776 scraped successfully
Page 435/1776 scraped successfully
Page 436/1776 scraped successfully
Page 437/1776 scraped successfully
Page 438/1776 scraped successfully
Page 439/1776 scraped successfully
Page 440/1776 scraped successfully
Page 441/1776 scraped successfully
Page 442/1776 scraped successfully
Page 443/1776 scraped successfully
Page 444/1776 scraped successfully
Page 445/1776 scraped successfully
Page 446/1776 scraped successfully
Page 447/1776 scraped successfully
Page 448/1776 scraped successfully
Page 449/1776 scraped successfully
Page 450/1776 scraped successfully
Page 451/1776 scraped successfully
Page 452/1776 scraped successfully
Page 453/1776 scraped successfully
Page 454/1776 scraped successfully
Page 455/1776 scraped successfully
Page 456/1776 scraped successfully
Page 457/1776 scraped successfully
Page 458/1776 scraped successfully
Page 459/1776 scraped successfully
Page 460/1776 scraped successfully
Page 461/1776 scraped successfully
Page 462/1776 scraped successfully
Page 463/1776 scraped successfully
Page 464/1776 scraped successfully
Page 465/1776 scraped successfully
Page 466/1776 scraped successfully
Page 467/1776 scraped successfully
Page 468/1776 scraped successfully
Page 469/1776 scraped successfully
Page 470/1776 scraped successfully
Page 471/1776 scraped successfully
Page 472/1776 scraped successfully
Page 473/1776 scraped successfully
Page 474/1776 scraped successfully
Page 475/1776 scraped successfully
Page 476/1776 scraped successfully
Page 477/1776 scraped successfully
Page 478/1776 scraped successfully
Page 479/1776 scraped successfully
Page 480/1776 scraped successfully
Page 481/1776 scraped successfully
Page 482/1776 scraped successfully
Page 483/1776 scraped successfully
Page 484/1776 scraped successfully
Page 485/1776 scraped successfully
Page 486/1776 scraped successfully
Page 487/1776 scraped successfully
Page 488/1776 scraped successfully
Page 489/1776 scraped successfully
Page 490/1776 scraped successfully
Page 491/1776 scraped successfully
Page 492/1776 scraped successfully
Page 493/1776 scraped successfully
Page 494/1776 scraped successfully
Page 495/1776 scraped successfully
Page 496/1776 scraped successfully
Page 497/1776 scraped successfully
Page 498/1776 scraped successfully
Page 499/1776 scraped successfully
Page 500/1776 scraped successfully
Page 501/1776 scraped successfully
Page 502/1776 scraped successfully
Page 503/1776 scraped successfully
Page 504/1776 scraped successfully
Page 505/1776 scraped successfully
Page 506/1776 scraped successfully
Page 507/1776 scraped successfully
Page 508/1776 scraped successfully
Page 509/1776 scraped successfully
Page 510/1776 scraped successfully
Page 511/1776 scraped successfully
Page 512/1776 scraped successfully
Page 513/1776 scraped successfully
Page 514/1776 scraped successfully
Page 515/1776 scraped successfully
Page 516/1776 scraped successfully
Page 517/1776 scraped successfully
Page 518/1776 scraped successfully
Page 519/1776 scraped successfully
Page 520/1776 scraped successfully
Page 521/1776 scraped successfully
Page 522/1776 scraped successfully
Page 523/1776 scraped successfully
Page 524/1776 scraped successfully
Page 525/1776 scraped successfully
Page 526/1776 scraped successfully
Page 527/1776 scraped successfully
Page 528/1776 scraped successfully
Page 529/1776 scraped successfully
Page 530/1776 scraped successfully
Page 531/1776 scraped successfully
Page 532/1776 scraped successfully
Page 533/1776 scraped successfully
Page 534/1776 scraped successfully
Page 535/1776 scraped successfully
Page 536/1776 scraped successfully
Page 537/1776 scraped successfully
Page 538/1776 scraped successfully
Page 539/1776 scraped successfully
Page 540/1776 scraped successfully
Page 541/1776 scraped successfully
Page 542/1776 scraped successfully
Page 543/1776 scraped successfully
Page 544/1776 scraped successfully
Page 545/1776 scraped successfully
Page 546/1776 scraped successfully
Page 547/1776 scraped successfully
Page 548/1776 scraped successfully
Page 549/1776 scraped successfully
Page 550/1776 scraped successfully
Page 551/1776 scraped successfully
Page 552/1776 scraped successfully
Page 553/1776 scraped successfully
Page 554/1776 scraped successfully
Page 555/1776 scraped successfully
Page 556/1776 scraped successfully
Page 557/1776 scraped successfully
Page 558/1776 scraped successfully
Page 559/1776 scraped successfully
Page 560/1776 scraped successfully
Page 561/1776 scraped successfully
Page 562/1776 scraped successfully
Page 563/1776 scraped successfully
Page 564/1776 scraped successfully
Page 565/1776 scraped successfully
Page 566/1776 scraped successfully
Page 567/1776 scraped successfully
Page 568/1776 scraped successfully
Page 569/1776 scraped successfully
Page 570/1776 scraped successfully
Page 571/1776 scraped successfully
Page 572/1776 scraped successfully
Page 573/1776 scraped successfully
Page 574/1776 scraped successfully
Page 575/1776 scraped successfully

In [37]:
df = pd.read_csv('./all_pages_data.csv')

In [38]:
df.shape

(90574, 4)

In [39]:
df.head()

         Date      Time  Generation(MW)  Demand(MW)
0  25-03-2025  17:00:00         13261.0       13261
1  25-03-2025  16:00:00         13205.0       13205
2  25-03-2025  15:00:00         13302.0       13302
3  25-03-2025  14:00:00         13253.0       13253
4  25-03-2025  13:00:00         13048.0       13048

In [40]:
df.duplicate()

AttributeError: 'DataFrame' object has no attribute 'duplicate'

In [41]:
df.duplicated().sum()

186

In [43]:
df[df.duplicated()]

             Date      Time  Generation(MW)  Demand(MW)
4951   08-09-2024  17:00:00         12411.0       14200
9060   28-03-2024  08:00:00          9820.0        9820
9133   25-03-2024  10:00:00         10323.0       10323
23495  28-08-2022  23:00:00         13364.0       14000
23624  23-08-2022  20:00:00         13383.0       14000
...           ...       ...             ...         ...
88560  07-07-2015  13:00:00          6801.0        6801
89313  08-06-2015  01:00:00          7573.0        7573
89383  06-06-2015  06:00:00          6066.0        6066
89484  02-06-2015  01:00:00          6440.0        6440
89664  26-05-2015  16:00:00          6421.0        6421

[186 rows x 4 columns]

In [44]:
df.head()

         Date      Time  Generation(MW)  Demand(MW)
0  25-03-2025  17:00:00         13261.0       13261
1  25-03-2025  16:00:00         13205.0       13205
2  25-03-2025  15:00:00         13302.0       13302
3  25-03-2025  14:00:00         13253.0       13253
4  25-03-2025  13:00:00         13048.0       13048

In [45]:
df.head(15)

          Date      Time  Generation(MW)  Demand(MW)
0   25-03-2025  17:00:00         13261.0       13261
1   25-03-2025  16:00:00         13205.0       13205
2   25-03-2025  15:00:00         13302.0       13302
3   25-03-2025  14:00:00         13253.0       13253
4   25-03-2025  13:00:00         13048.0       13048
5   25-03-2025  12:00:00         12734.0       12734
6   25-03-2025  11:00:00         12251.0       12251
7   25-03-2025  10:00:00         11940.0       11940
8   25-03-2025  09:00:00         11375.0       11375
9   25-03-2025  08:00:00         10826.0       10826
10  25-03-2025  07:00:00         10066.0       10066
11  25-03-2025  06:00:00          9802.0        9802
12  25-03-2025  05:00:00         10496.0       10496
13  25-03-2025  04:00:00         11745.0       11745
14  25-03-2025  03:00:00         11754.0       11754